# Generated by Django 4.1.2 on 2022-11-14 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('account_img', models.ImageField(upload_to='profiles_imgs')),
                ('follow_set', models.ManyToManyField(blank=True, to='carrotStagram.account')),
                ('following_set', models.ManyToManyField(blank=True, to='carrotStagram.account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('post_img', models.ImageField(upload_to='post_imgs')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrotStagram.account')),
            ],
        ),
    ]
