# Generated by Django 4.1.3 on 2022-11-17 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carrotStagram", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="follow_set",),
        migrations.RemoveField(model_name="account", name="following_set",),
        migrations.AddField(
            model_name="account",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="account_followers", to="carrotStagram.account"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="followings",
            field=models.ManyToManyField(
                blank=True,
                related_name="account_followings",
                to="carrotStagram.account",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="password",
            field=models.CharField(default="0000", max_length=50),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="post", name="description", field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                ("people", models.ManyToManyField(to="carrotStagram.account")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carrotStagram.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("person", models.ManyToManyField(to="carrotStagram.account")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carrotStagram.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentLikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carrotStagram.comments",
                    ),
                ),
                ("people", models.ManyToManyField(to="carrotStagram.account")),
            ],
        ),
    ]
