# Generated by Django 4.1.3 on 2022-11-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carrotStagram", "0003_alter_account_account_img_alter_post_link"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="followings",),
    ]
