# Generated by Django 4.1.3 on 2022-11-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carrotStagram", "0004_remove_account_followings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account", old_name="followers", new_name="follows",
        ),
    ]
