# Generated by Django 4.1.3 on 2022-11-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrotStagram", "0005_rename_followers_account_follows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_img",
            field=models.ImageField(upload_to="profiles_imgs"),
        ),
        migrations.AlterField(
            model_name="account",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="carrotStagram.account"
            ),
        ),
        migrations.AlterField(
            model_name="commentlikes",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="likes", name="count", field=models.IntegerField(default=0),
        ),
    ]
