# Generated by Django 4.1.3 on 2022-11-27 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "carrotStagram",
            "0006_alter_account_account_img_alter_account_follows_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="account_img",),
        migrations.RemoveField(model_name="post", name="post_img",),
    ]
