# Generated by Django 4.1.3 on 2022-11-28 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carrotStagram", "0007_remove_account_account_img_remove_post_post_img"),
    ]

    operations = [
        migrations.RemoveField(model_name="comments", name="person",),
        migrations.AddField(
            model_name="comments",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="carrotStagram.account",
            ),
            preserve_default=False,
        ),
    ]
